using System;
using System.Collections.Generic;
using UnityEngine;

/// <summary>
/// Companion component for a generic placeable installation spot that turns the installed prefab into a wall drill producer.
/// The generic PlaceableInstallationSpot still owns placement, ghost preview, obstruction checks, hotbar consumption and installed item persistence.
/// This component only owns wall-drill production data and initializes the installed DrillMachine runtime.
/// </summary>
[DisallowMultipleComponent]
public sealed class WallDrillInstallationSpot : MonoBehaviour
{
    /// <summary>
    /// Weighted ore option used by this special drill vein when generating stored drill output.
    /// </summary>
    [Serializable]
    public sealed class WeightedOreEntry
    {
        [Tooltip("Ore definition that can be generated by this wall drill spot.")]
        [SerializeField] private OreDefinition OreDefinition;

        [Tooltip("Relative random weight. Higher values make this ore more likely than other entries in the same list.")]
        [SerializeField] private int Weight = 1;

        /// <summary>
        /// Gets the configured ore definition.
        /// </summary>
        public OreDefinition GetOreDefinition()
        {
            return OreDefinition;
        }

        /// <summary>
        /// Gets the safe relative random weight.
        /// </summary>
        public int GetWeight()
        {
            return Mathf.Max(0, Weight);
        }
    }

    [Header("References")]
    [Tooltip("Generic placement spot that owns installation, obstruction validation, ghost preview and installed item persistence.")]
    [SerializeField] private PlaceableInstallationSpot InstallationSpot;

    [Tooltip("Runtime ore service used by installed drill machines to create ore payloads and spawn claimed output.")]
    [SerializeField] private OreRuntimeService OreRuntimeService;

    [Tooltip("Upgrade manager used by installed drill machines for global wall drill modifiers.")]
    [SerializeField] private UpgradeManager UpgradeManager;

    [Header("Production")]
    [Tooltip("Ores that this special drill vein can generate. Use one entry for a pure vein or several weighted entries for a mixed vein.")]
    [SerializeField] private List<WeightedOreEntry> AvailableOres = new List<WeightedOreEntry>();

    [Tooltip("Base seconds needed to generate one internal ore payload before upgrade modifiers.")]
    [SerializeField] private float ProductionInterval = 4f;

    [Tooltip("Base amount of ore payloads stored internally before the drill pauses.")]
    [SerializeField] private int MaxStoredOreCount = 4;

    [Header("Debug")]
    [Tooltip("Logs wall drill spot initialization, save restoration and production table issues.")]
    [SerializeField] private bool DebugLogs = false;

    /// <summary>
    /// Installed drill runtime currently controlled by this special spot.
    /// </summary>
    private DrillMachine CurrentDrillMachine;

    /// <summary>
    /// Remaining production timer restored from save before the installed drill is available.
    /// </summary>
    private float PendingRemainingProductionTimer = -1f;

    /// <summary>
    /// Stored ore payloads restored from save before the installed drill is available.
    /// </summary>
    private readonly List<OreItemData> PendingStoredOreItems = new List<OreItemData>();

    /// <summary>
    /// Whether a saved drill runtime state is waiting to be applied to the installed visual.
    /// </summary>
    private bool HasPendingRuntimeState;

    /// <summary>
    /// Resolves local references.
    /// </summary>
    private void Awake()
    {
        EnsureReferences();
    }

    /// <summary>
    /// Subscribes to installation events so the installed DrillMachine can be initialized without owning placement logic.
    /// </summary>
    private void OnEnable()
    {
        EnsureReferences();

        if (InstallationSpot != null)
        {
            InstallationSpot.InstallationChanged += HandleInstallationChanged;
            InstallationSpot.InstallationCleared += HandleInstallationCleared;
        }
    }

    /// <summary>
    /// Unsubscribes from installation events.
    /// </summary>
    private void OnDisable()
    {
        if (InstallationSpot != null)
        {
            InstallationSpot.InstallationChanged -= HandleInstallationChanged;
            InstallationSpot.InstallationCleared -= HandleInstallationCleared;
        }
    }

    /// <summary>
    /// Initializes an already installed drill visual when the scene starts with a pre-existing state.
    /// </summary>
    private void Start()
    {
        RefreshInstalledDrillFromCurrentSpotState();
    }

    /// <summary>
    /// Ensures optional references are resolved from the scene when not assigned manually.
    /// </summary>
    private void EnsureReferences()
    {
        if (InstallationSpot == null)
        {
            InstallationSpot = GetComponent<PlaceableInstallationSpot>();
        }

        if (OreRuntimeService == null)
        {
            OreRuntimeService = FindFirstObjectByType<OreRuntimeService>();
        }

        if (UpgradeManager == null)
        {
            UpgradeManager = FindFirstObjectByType<UpgradeManager>();
        }
    }

    /// <summary>
    /// Gets whether this special drill spot currently has an installed and initialized drill machine.
    /// </summary>
    public bool GetHasInstalledDrill()
    {
        return CurrentDrillMachine != null;
    }

    /// <summary>
    /// Gets the current remaining production timer from the installed drill.
    /// </summary>
    public float GetCurrentRemainingProductionTimer()
    {
        return CurrentDrillMachine != null ? CurrentDrillMachine.GetRemainingProductionTimer() : 0f;
    }

    /// <summary>
    /// Gets a copy of the internally stored ore payloads from the installed drill.
    /// </summary>
    public List<OreItemData> GetStoredOreItemsSnapshot()
    {
        return CurrentDrillMachine != null
            ? CurrentDrillMachine.GetStoredOreItemsSnapshot()
            : new List<OreItemData>();
    }

    /// <summary>
    /// Applies saved runtime state for the installed drill machine.
    /// The generic placeable installation state must be restored before this method for immediate initialization.
    /// </summary>
    /// <param name="RemainingProductionTimer">Saved remaining production timer.</param>
    /// <param name="StoredOreItems">Saved internal ore payloads.</param>
    public void ApplySavedState(float RemainingProductionTimer, IReadOnlyList<OreItemData> StoredOreItems)
    {
        PendingRemainingProductionTimer = Mathf.Max(0f, RemainingProductionTimer);
        PendingStoredOreItems.Clear();

        if (StoredOreItems != null)
        {
            for (int Index = 0; Index < StoredOreItems.Count; Index++)
            {
                OreItemData OreItem = StoredOreItems[Index];

                if (OreItem == null || OreItem.GetOreDefinition() == null)
                {
                    continue;
                }

                PendingStoredOreItems.Add(OreItem);
            }
        }

        HasPendingRuntimeState = true;
        RefreshInstalledDrillFromCurrentSpotState();
    }

    /// <summary>
    /// Resolves one ore definition from the configured weighted production table.
    /// </summary>
    /// <returns>Selected ore definition, or null when the table is invalid.</returns>
    public OreDefinition ResolveRandomOreDefinition()
    {
        int TotalWeight = 0;

        for (int Index = 0; Index < AvailableOres.Count; Index++)
        {
            WeightedOreEntry Entry = AvailableOres[Index];

            if (Entry == null || Entry.GetOreDefinition() == null)
            {
                continue;
            }

            TotalWeight += Entry.GetWeight();
        }

        if (TotalWeight <= 0)
        {
            Log("No valid weighted ore entries are configured.");
            return null;
        }

        int Roll = UnityEngine.Random.Range(0, TotalWeight);

        for (int Index = 0; Index < AvailableOres.Count; Index++)
        {
            WeightedOreEntry Entry = AvailableOres[Index];

            if (Entry == null || Entry.GetOreDefinition() == null)
            {
                continue;
            }

            int EntryWeight = Entry.GetWeight();

            if (EntryWeight <= 0)
            {
                continue;
            }

            if (Roll < EntryWeight)
            {
                return Entry.GetOreDefinition();
            }

            Roll -= EntryWeight;
        }

        return null;
    }

    /// <summary>
    /// Releases the current drill reference when the installed drill is destroyed.
    /// </summary>
    /// <param name="DrillMachine">Drill machine being released.</param>
    public void NotifyDrillReleased(DrillMachine DrillMachine)
    {
        if (CurrentDrillMachine != DrillMachine)
        {
            return;
        }

        CurrentDrillMachine = null;
        Log("Installed drill machine released.");
    }

    /// <summary>
    /// Reacts to a generic placeable installation and initializes the installed DrillMachine if present.
    /// </summary>
    private void HandleInstallationChanged(PlaceableInstallationSpot Spot, ItemInstance InstalledItem, GameObject InstalledVisual)
    {
        RefreshInstalledDrill(InstalledItem, InstalledVisual);
    }

    /// <summary>
    /// Clears runtime references when the generic installation spot is emptied or replaced.
    /// </summary>
    private void HandleInstallationCleared(PlaceableInstallationSpot Spot)
    {
        CurrentDrillMachine = null;
        HasPendingRuntimeState = false;
        PendingRemainingProductionTimer = -1f;
        PendingStoredOreItems.Clear();
        Log("Generic installation was cleared. Wall drill runtime state was reset.");
    }

    /// <summary>
    /// Refreshes the installed drill from the current generic installation spot state.
    /// </summary>
    private void RefreshInstalledDrillFromCurrentSpotState()
    {
        if (InstallationSpot == null)
        {
            return;
        }

        RefreshInstalledDrill(
            InstallationSpot.CreateInstalledItemSnapshot(),
            InstallationSpot.GetCurrentInstalledVisual());
    }

    /// <summary>
    /// Initializes the DrillMachine component found inside the installed visual.
    /// </summary>
    private void RefreshInstalledDrill(ItemInstance InstalledItem, GameObject InstalledVisual)
    {
        CurrentDrillMachine = null;

        if (InstalledItem == null || InstalledVisual == null)
        {
            return;
        }

        DrillMachine DrillMachine = InstalledVisual.GetComponent<DrillMachine>() ?? InstalledVisual.GetComponentInChildren<DrillMachine>(true);

        if (DrillMachine == null)
        {
            Log("Installed prefab has no DrillMachine component. This is allowed for non-drill placeables, but invalid for wall drill spots.");
            return;
        }

        IReadOnlyList<OreItemData> StoredOreItems = HasPendingRuntimeState
            ? PendingStoredOreItems
            : null;

        float RemainingTimer = HasPendingRuntimeState
            ? PendingRemainingProductionTimer
            : -1f;

        DrillMachine.Initialize(
            this,
            OreRuntimeService,
            UpgradeManager,
            InstalledItem.GetDefinition(),
            ProductionInterval,
            MaxStoredOreCount,
            RemainingTimer,
            StoredOreItems);

        CurrentDrillMachine = DrillMachine;
        HasPendingRuntimeState = false;
        PendingRemainingProductionTimer = -1f;
        PendingStoredOreItems.Clear();

        Log("Installed wall drill machine initialized.");
    }

    /// <summary>
    /// Writes a debug log when enabled.
    /// </summary>
    private void Log(string Message)
    {
        if (!DebugLogs)
        {
            return;
        }

        Debug.Log("[WallDrillInstallationSpot] " + Message, this);
    }
}
