using UnityEngine;

/// <summary>
/// Controls explicit sleep and wake policy for a dynamic carryable rigidbody.
/// The object may sleep only when it is dynamic, idle, supported and not blocked by an external system.
/// </summary>
[DisallowMultipleComponent]
public sealed class CarryableSleepController : MonoBehaviour
{
    [System.Serializable]
    public struct SleepSettings
    {
        [Tooltip("Seconds the rigidbody must remain idle before sleeping.")]
        public float RequiredStillTime;

        [Tooltip("Maximum linear speed allowed to consider the rigidbody idle.")]
        public float MaxLinearSpeed;

        [Tooltip("Maximum angular speed allowed to consider the rigidbody idle.")]
        public float MaxAngularSpeed;

        [Tooltip("Minimum upward normal required to consider a collision as supporting ground.")]
        public float MinimumSupportNormalY;
    }

    [Header("Sleep")]
    [Tooltip("Configuration used to decide when the carryable may sleep.")]
    [SerializeField]
    private SleepSettings Settings = new SleepSettings
    {
        RequiredStillTime = 0.25f,
        MaxLinearSpeed = 0.05f,
        MaxAngularSpeed = 0.075f,
        MinimumSupportNormalY = 0.45f
    };

    /// <summary>
    /// Returns true if the rigidbody is currently blocked from sleeping.
    /// </summary>
    public bool IsSleepBlocked => SleepBlockCount > 0;

    /// <summary>
    /// Accumulated idle time while all sleep conditions are satisfied.
    /// </summary>
    private float IdleTimer;

    /// <summary>
    /// Number of active external sleep blockers.
    /// </summary>
    private int SleepBlockCount;

    /// <summary>
    /// Whether a valid support contact was detected during the current simulation step.
    /// </summary>
    private bool HasSupportThisStep;

    /// <summary>
    /// Rigidbodies currently managed by this sleep controller.
    /// </summary>
    private Rigidbody RigidbodyComponent;

    /// <summary>
    /// Caches the target rigidbody.
    /// </summary>
    private void Awake()
    {
        RigidbodyComponent = GetComponent<Rigidbody>();
    }

    /// <summary>
    /// Blocks sleeping until the matching unblock call happens.
    /// </summary>
    public void PushSleepBlock()
    {
        SleepBlockCount++;
        WakeUp();
    }

    /// <summary>
    /// Removes one active sleep block.
    /// </summary>
    public void PopSleepBlock()
    {
        SleepBlockCount = Mathf.Max(0, SleepBlockCount - 1);
    }

    /// <summary>
    /// Forces the rigidbody awake immediately.
    /// </summary>
    public void WakeUp()
    {
        IdleTimer = 0f;

        if (RigidbodyComponent != null)
        {
            RigidbodyComponent.WakeUp();
        }
    }

    /// <summary>
    /// Evaluates sleeping conditions for the current fixed step.
    /// </summary>
    /// <param name="CanSleep">True when the current high-level carryable mode allows sleep.</param>
    public void Tick(bool CanSleep)
    {
        if (RigidbodyComponent == null || RigidbodyComponent.isKinematic)
        {
            HasSupportThisStep = false;
            IdleTimer = 0f;
            return;
        }

        bool IsIdle =
            RigidbodyComponent.linearVelocity.sqrMagnitude <= Settings.MaxLinearSpeed * Settings.MaxLinearSpeed &&
            RigidbodyComponent.angularVelocity.sqrMagnitude <= Settings.MaxAngularSpeed * Settings.MaxAngularSpeed;

        bool MaySleepNow = CanSleep && !IsSleepBlocked && HasSupportThisStep && IsIdle;

        if (!MaySleepNow)
        {
            IdleTimer = 0f;
            HasSupportThisStep = false;
            return;
        }

        IdleTimer += Time.fixedDeltaTime;

        if (IdleTimer >= Settings.RequiredStillTime && !RigidbodyComponent.IsSleeping())
        {
            RigidbodyComponent.Sleep();
        }

        HasSupportThisStep = false;
    }

    /// <summary>
    /// Collects valid support contacts generated by this rigidbody hierarchy.
    /// </summary>
    /// <param name="Collision">Collision data.</param>
    private void OnCollisionStay(Collision Collision)
    {
        EvaluateSupportContacts(Collision);
    }

    /// <summary>
    /// Collects valid support contacts generated by this rigidbody hierarchy.
    /// </summary>
    /// <param name="Collision">Collision data.</param>
    private void OnCollisionEnter(Collision Collision)
    {
        EvaluateSupportContacts(Collision);
    }

    /// <summary>
    /// Evaluates whether any contact in the collision can support the rigidbody from below.
    /// </summary>
    /// <param name="Collision">Collision data.</param>
    private void EvaluateSupportContacts(Collision Collision)
    {
        if (Collision == null)
        {
            return;
        }

        for (int ContactIndex = 0; ContactIndex < Collision.contactCount; ContactIndex++)
        {
            ContactPoint Contact = Collision.GetContact(ContactIndex);
            if (Contact.normal.y >= Settings.MinimumSupportNormalY)
            {
                HasSupportThisStep = true;
                return;
            }
        }
    }
}