using UnityEngine;

/// <summary>
/// Immutable request sent by any mining source to a mineable target.
/// It contains the source context, damage, tier and purity bonus data required to resolve the hit deterministically.
/// </summary>
public readonly struct MiningHitRequest
{
    /// <summary>
    /// Damage applied to the target ore durability when the hit is accepted.
    /// </summary>
    public readonly float MiningDamage;

    /// <summary>
    /// Mining tier provided by the tool or machine that caused the hit.
    /// </summary>
    public readonly MiningTier MiningTier;

    /// <summary>
    /// Minimum flat purity percent bonus added to each ore generated by this accepted breaking hit.
    /// </summary>
    public readonly float PurityBonusPercentMin;

    /// <summary>
    /// Maximum flat purity percent bonus added to each ore generated by this accepted breaking hit.
    /// </summary>
    public readonly float PurityBonusPercentMax;

    /// <summary>
    /// Durability consumed by the source tool if the hit is accepted.
    /// The mineable target does not spend durability directly; the tool consumes this after receiving the result.
    /// </summary>
    public readonly float DurabilityCost;

    /// <summary>
    /// World context of the mining hit.
    /// </summary>
    public readonly MiningHitContext HitContext;

    /// <summary>
    /// Creates a new mining hit request.
    /// </summary>
    /// <param name="MiningDamageValue">Raw mining damage applied by the source.</param>
    /// <param name="MiningTierValue">Mining tier provided by the source.</param>
    /// <param name="PurityBonusPercentMinValue">Minimum flat purity percent bonus added to generated drops.</param>
    /// <param name="PurityBonusPercentMaxValue">Maximum flat purity percent bonus added to generated drops.</param>
    /// <param name="DurabilityCostValue">Durability cost consumed by the source tool after an accepted hit.</param>
    /// <param name="HitContextValue">World hit context.</param>
    public MiningHitRequest(
        float MiningDamageValue,
        MiningTier MiningTierValue,
        float PurityBonusPercentMinValue,
        float PurityBonusPercentMaxValue,
        float DurabilityCostValue,
        MiningHitContext HitContextValue)
    {
        MiningDamage = Mathf.Max(0f, MiningDamageValue);
        MiningTier = MiningTierValue == MiningTier.None ? MiningTier.TierI : MiningTierValue;
        PurityBonusPercentMin = Mathf.Clamp(Mathf.Min(PurityBonusPercentMinValue, PurityBonusPercentMaxValue), -100f, 100f);
        PurityBonusPercentMax = Mathf.Clamp(Mathf.Max(PurityBonusPercentMinValue, PurityBonusPercentMaxValue), -100f, 100f);
        DurabilityCost = Mathf.Max(0f, DurabilityCostValue);
        HitContext = HitContextValue;
    }

    /// <summary>
    /// Creates a new mining hit request with no purity bonus.
    /// </summary>
    /// <param name="MiningDamageValue">Raw mining damage applied by the source.</param>
    /// <param name="MiningTierValue">Mining tier provided by the source.</param>
    /// <param name="DurabilityCostValue">Durability cost consumed by the source tool after an accepted hit.</param>
    /// <param name="HitContextValue">World hit context.</param>
    public MiningHitRequest(
        float MiningDamageValue,
        MiningTier MiningTierValue,
        float DurabilityCostValue,
        MiningHitContext HitContextValue)
        : this(MiningDamageValue, MiningTierValue, 0f, 0f, DurabilityCostValue, HitContextValue)
    {
    }
}
