using System;
using System.Collections.Generic;
using UnityEngine;

/// <summary>
/// Static definition for one mineable ore type.
/// This asset owns identity, world prefabs, mining requirements, physical weight and credit value ranges.
/// Runtime purity, size and final value are resolved by OreRuntimeService when an ore pickup is created.
/// </summary>
[CreateAssetMenu(fileName = "OreDefinition_", menuName = "Game/Mining/Ore Definition")]
public sealed class OreDefinition : ScriptableObject
{
    [Serializable]
    public sealed class OrePropertyRange
    {
        [Tooltip("Runtime property generated on each dropped ore instance.")]
        [SerializeField] private OrePropertyType PropertyType = OrePropertyType.None;

        [Tooltip("Minimum generated value for this property.")]
        [SerializeField] private float MinValue = 0f;

        [Tooltip("Maximum generated value for this property.")]
        [SerializeField] private float MaxValue = 1f;

        [Tooltip("If true, global upgrades can modify the generated property value.")]
        [SerializeField] private bool AffectedByUpgrades = true;

        /// <summary>
        /// Gets the property type generated by this range.
        /// </summary>
        public OrePropertyType GetPropertyType() => PropertyType;

        /// <summary>
        /// Gets the minimum generated value.
        /// </summary>
        public float GetMinValue() => Mathf.Min(MinValue, MaxValue);

        /// <summary>
        /// Gets the maximum generated value.
        /// </summary>
        public float GetMaxValue() => Mathf.Max(MinValue, MaxValue);

        /// <summary>
        /// Gets whether upgrades can affect this generated value.
        /// </summary>
        public bool GetAffectedByUpgrades() => AffectedByUpgrades;
    }

    [Header("Identity")]
    [Tooltip("Stable ore identifier used by saves, upgrades and progression systems.")]
    [SerializeField] private string OreId;

    [Tooltip("Display name shown in scanner UI and debug tools.")]
    [SerializeField] private string DisplayName;

    [Tooltip("Optional ore icon used by UI.")]
    [SerializeField] private Sprite Icon;

    [Header("World")]
    [Tooltip("Mineable vein prefab spawned by generic ore spawn points.")]
    [SerializeField] private GameObject VeinPrefab;

    [Tooltip("Default dropped ore prefab used as fallback when the visual variants list is empty.")]
    [SerializeField] private GameObject DroppedOrePrefab;

    [Tooltip("Optional list of dropped ore visual prefabs. A random one is selected every time a drop is spawned.")]
    [SerializeField] private List<GameObject> DroppedOreVisualPrefabs = new();

    [Header("Mining")]
    [Tooltip("Minimum mining tier required to damage this ore. Lower tier tools will be rejected without consuming durability.")]
    [SerializeField] private MiningTier RequiredMiningTier = MiningTier.TierI;

    [Tooltip("Base amount of mining damage required to break this ore vein.")]
    [SerializeField] private int BaseMiningDurability = 3;

    [Tooltip("Seconds required before this ore vein regrows after being depleted.")]
    [SerializeField] private float BaseRespawnTime = 30f;

    [Tooltip("Minimum amount of physical ore pickups spawned when this vein breaks.")]
    [SerializeField] private int BaseDropCountMin = 1;

    [Tooltip("Maximum amount of physical ore pickups spawned when this vein breaks.")]
    [SerializeField] private int BaseDropCountMax = 2;

    [Header("Weight")]
    [Tooltip("Base physical weight contributed by each dropped ore before purity and size multipliers.")]
    [SerializeField] private float BaseWeightValue = 10f;

    [Header("Economy")]
    [Tooltip("Minimum base credit value rolled for each dropped ore before purity, size and upgrade modifiers.")]
    [SerializeField] private float BaseCreditValueMin = 3f;

    [Tooltip("Maximum base credit value rolled for each dropped ore before purity, size and upgrade modifiers.")]
    [SerializeField] private float BaseCreditValueMax = 6f;


    [Header("Properties")]
    [Tooltip("Runtime property ranges generated on each dropped ore pickup.")]
    [SerializeField] private List<OrePropertyRange> PropertyRanges = new();

    /// <summary>
    /// Gets the stable ore identifier.
    /// </summary>
    public string GetOreId() => OreId;

    /// <summary>
    /// Gets the display name shown to the player.
    /// </summary>
    public string GetDisplayName() => DisplayName;

    /// <summary>
    /// Gets the optional ore icon.
    /// </summary>
    public Sprite GetIcon() => Icon;

    /// <summary>
    /// Gets the mineable vein prefab used by generic ore spawners.
    /// </summary>
    public GameObject GetVeinPrefab() => VeinPrefab;

    /// <summary>
    /// Gets the single dropped ore prefab fallback.
    /// </summary>
    public GameObject GetDroppedOrePrefab() => DroppedOrePrefab;

    /// <summary>
    /// Gets the optional dropped ore visual prefab variants.
    /// </summary>
    public IReadOnlyList<GameObject> GetDroppedOreVisualPrefabs() => DroppedOreVisualPrefabs;

    /// <summary>
    /// Gets the minimum mining tier required to damage this ore.
    /// </summary>
    public MiningTier GetRequiredMiningTier() => RequiredMiningTier == MiningTier.None ? MiningTier.TierI : RequiredMiningTier;

    /// <summary>
    /// Gets the base mining durability required before this ore breaks.
    /// </summary>
    public int GetBaseMiningDurability() => Mathf.Max(1, BaseMiningDurability);


    /// <summary>
    /// Gets the base respawn time in seconds.
    /// </summary>
    public float GetBaseRespawnTime() => Mathf.Max(0f, BaseRespawnTime);

    /// <summary>
    /// Gets the minimum amount of drops created when this ore breaks.
    /// </summary>
    public int GetBaseDropCountMin() => Mathf.Max(0, BaseDropCountMin);

    /// <summary>
    /// Gets the maximum amount of drops created when this ore breaks.
    /// </summary>
    public int GetBaseDropCountMax() => Mathf.Max(GetBaseDropCountMin(), BaseDropCountMax);

    /// <summary>
    /// Gets the base physical weight for one dropped ore pickup.
    /// </summary>
    public float GetBaseWeightValue() => Mathf.Max(0f, BaseWeightValue);

    /// <summary>
    /// Gets the minimum base credit value for one dropped ore pickup.
    /// </summary>
    public float GetBaseCreditValueMin() => CurrencyMath.RoundCurrency(Mathf.Max(0f, BaseCreditValueMin));

    /// <summary>
    /// Gets the maximum base credit value for one dropped ore pickup.
    /// </summary>
    public float GetBaseCreditValueMax() => CurrencyMath.RoundCurrency(Mathf.Max(GetBaseCreditValueMin(), BaseCreditValueMax));


    /// <summary>
    /// Gets runtime property generation ranges for this ore.
    /// </summary>
    public IReadOnlyList<OrePropertyRange> GetPropertyRanges() => PropertyRanges;

    /// <summary>
    /// Returns a random valid dropped ore prefab.
    /// Uses the visual variants list when available and falls back to the single fallback prefab otherwise.
    /// </summary>
    /// <returns>Dropped ore prefab or null when none is configured.</returns>
    public GameObject GetRandomDroppedOrePrefab()
    {
        if (DroppedOreVisualPrefabs != null && DroppedOreVisualPrefabs.Count > 0)
        {
            List<GameObject> ValidPrefabs = null;

            for (int Index = 0; Index < DroppedOreVisualPrefabs.Count; Index++)
            {
                if (DroppedOreVisualPrefabs[Index] == null)
                {
                    continue;
                }

                if (ValidPrefabs == null)
                {
                    ValidPrefabs = new List<GameObject>();
                }

                ValidPrefabs.Add(DroppedOreVisualPrefabs[Index]);
            }

            if (ValidPrefabs != null && ValidPrefabs.Count > 0)
            {
                int RandomIndex = UnityEngine.Random.Range(0, ValidPrefabs.Count);
                return ValidPrefabs[RandomIndex];
            }
        }

        return DroppedOrePrefab;
    }
}
